name: Sanity

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  sanity:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11, 3.12, 3.13]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Update pip
        run: python -m pip install --upgrade pip wheel setuptools hatch
  
      - name: Install in editable mode
        run: python -m pip install -e .

      - name: Check help message
        run: python -m flowco --help

      - name: Check calling executables directly
        run: |
          flowco --help

      - name: build wheel
        run: hatch build -t wheel

      - name: install wheel
        run: python -m pip install dist/flowco-*.whl

      - name: Check help message
        run: python -m flowco --help


